spring:
  application:
    name: user_service
  # Currently uses an Oracle H2 test database automatically created by jpa and then
  # populated by the data-h2.sql file in the src/main/resources folder
  datasource:
    url: jdbc:h2:mem:caliber;Mode=Oracle
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
# Set up Eureka home as an environment variable with the location of Eureka in order
# to use the eureka discovery client with this service
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}
# Service runs on port 9085
server:
  port: 9085