-- TRAINEES --

INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (1,'howard.johnson@hotmail.com','Howard Johnson','TRAINING',2003,'555-555-5555',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5500,'dlaut1@hotmail.com','Laut, Daniel','DROPPED',2150,'843-360-9205',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5501,'ckipp2@hotmail.com','Kipp, Charles','DROPPED',2150,'(480) 527-9139',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5502,'xinguang.huang1@gmail.com','Huang, Jason','DROPPED',2150,'208-830-8976',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5503,'osher.y.cohen@gmail.com','Cohen, Osher','EMPLOYED',2200,'347-524-1846','https://app.revature.com/profile/Osher/f341fc92cebe36b3753df749eeb57b2a','osher.y.cohen');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5504,'kchangfatt@gmail.com','Chang Fatt, Kyle','EMPLOYED',2200,'(917) 843-0464','https://app.revature.com/profile/kchangfatt/566988d360a8a0df93036e3e0d33e81f','kyle.changfatt');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5505,'nikolovski23@gmail.com','Nikolovski, Martino','EMPLOYED',2200,'347-593-9059','https://app.revature.com/profile/Martino/18411f7d60abb8d3ea9b8a12f9e32041','martino.23');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5506,'louisalopez93@gmail.com','Lopez, Louis','EMPLOYED',2200,'516-301-8490','https://app.revature.com/profile/LouisLopez/71fd9c8b9c4fc2fe20ec464e14e14c5d','louisalopez23');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5507,'syar0052@gmail.com','Yar, Shehar','EMPLOYED',2200,'(347) 653-0052','https://app.revature.com/profile/Shehar/f35ad0947a9108f7724aaadb3f0d311b','syar0052');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5508,'achen.this@gmail.com','Chen, Andrew','EMPLOYED',2200,'347-618-9852','https://app.revature.com/profile/AndrewChen/77a3861a405068e383f482fb2bcdc629','achen.this');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5509,'davidsibrian08@gmail.com','Sibrian, David','EMPLOYED',2200,'347-933-0847','https://app.revature.com/profile/davidsibrian08/fd4cf53dd3924a64a537f888b9713def','davidsibrian08_1');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5510,'karymacancela@gmail.com','Macancela, Karina','EMPLOYED',2200,'347-570-5804','https://app.revature.com/profile/kmacancela/4862d51e2c3940d37b5baf300e58962b','karymacancela');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5511,'shamlau23@gmail.com','Lau, Samuel','EMPLOYED',2200,'347-557-7626','https://app.revature.com/profile/shamlau/02c9c1073f9b3ab702f9c5db18fe9e6c','shamlau');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5512,'ychenq001@gmail.com','Chen, Yan','EMPLOYED',2200,'(347) 265-0886','https://app.revature.com/profile/ychen/bae900b010b8c778db2b8b93fafd3d67','YChenq001');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5513,'williams.andrew15@gmail.com','Williams, Andrew','EMPLOYED',2200,'914-255-5011','https://app.revature.com/profile/Gigantor15/c33772d90963ba311da91439c153ded4','williams.andrew15');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5514,'katz.rikki@gmail.com','Katz, Rikki','EMPLOYED',2200,'(516) 531-3671','https://app.revature.com/profile/RebeccaK/3d80c961cf1dab656b02aa6d1aaa95b4','rikkik13');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5515,'bcantos17@gmail.com','Cantos, Bryan','EMPLOYED',2200,'347-848-4163','https://app.revature.com/profile/bcantos17/1d1241150188ed37a992e84d4ee3ccf3','BCantos17');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5516,'travis.dacosta1@gmail.com','Dacosta, Travis','EMPLOYED',2200,'347-500-7612','https://app.revature.com/profile/tdacosta11/9c0a7e4de28a8898c2b9186debe0e7cb','travisdac');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5517,'ilysiarh@gmail.com','Siarheyeu, Ilya','EMPLOYED',2200,'347-334-1704','https://app.revature.com/profile/ilysiarh/1612b1d54369bfa052cb56c24334040f','ilysiarh');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5518,'wingz101@icloud.com','Fredericksen-Rasberry, Salim','DROPPED',2200,'(516) 825-1848',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5519,'bankole726@gmail.com','Thomas, Bankole','DROPPED',2200,'3476527223',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5520,'davedataram@gmail.com','Dataram, Dave','DROPPED',1,'347-986-0617',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5521,'azraelzzz@hotmail.com','In Choi, Hou','DROPPED',1,'(347) 459-2016',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5522,'chandradatgir@yahoo.com','Gir, Chandradat','DROPPED',1,'347-447-7487',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5523,'jcsanchez1218@yahoo.com','Carlos Sanchez, Juan','DROPPED',1,'(347) 641-8146',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5524,'mcartagenaez8@gmail.com','Cartagena, Michael','EMPLOYED',1,'347-782-4731','https://app.revature.com/profile/MichaelC/55b6b9a398dacdb90093a3088822d35c','mcart5566');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5525,'tanland20@gmail.com','Peralta, Yanilda','EMPLOYED',1,'347-638-1605','https://app.revature.com/profile/Synac/254a7187dfc32f6f50710a56bd8112f6','eclipsesunsettreesynch');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5526,'son.jack0218@gmail.com','Duong, Jack','EMPLOYED',1,'(646) 417-3976','https://app.revature.com/profile/imrjack/fab72b5d62b5965bcd22aabe0a9ee24b','imrjack');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5527,'hvalcin.grady@gmail.com','Valcin, Hendy','EMPLOYED',1,'347-272-0040','https://app.revature.com/profile/Hendy/4991db30a308e99aff23eead11daa716','live:196c1fe19236d6c6');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5528,'hossain.yahya@outlook.com','Yahya, Hossain','EMPLOYED',1,'347-595-0959','https://app.revature.com/profile/Hossain/56533488cfec931bbc8e43ba02f12190','live:hossain.yahya_1');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5529,'denise.j.montesdeoca@gmail.com','Montesdeoca, Denise','EMPLOYED',1,'347-536-7727','https://app.revature.com/profile/dmontesdeoca/4ddfb0697a3c1fff8d16e6a1ce46348c','live:55f3683c5bb7165c');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5530,'fareed.ali37@qmail.cuny.edu','Ali, Fareed','EMPLOYED',1,'347-526-5184','https://app.revature.com/profile/fareed/03198a1e81a3f4e32433a9e9c9db353e','live:bassph');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5531,'kamlam@live.com','Lam, Kam','TRAINING',1,'917-951-1138','https://app.revature.com/profile/Kamlam02/0b64db75d34cddd8b96f8091e44d57b7','live:89f575098655f2b');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5532,'sadat.t.ahmed@gmail.com','Ahmed, Sadat','EMPLOYED',1,'646-407-7707','https://app.revature.com/profile/SadatAhmed/9b198abd1d0d88022d593375b61ed041','sadat.t.ahmed');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5533,'pieryospp@gmail.com','Yos, Pier','EMPLOYED',1,'347-238-4965','https://app.revature.com/profile/Peacepapi/22e027610567ad08a4c6698a8dbfa74b','pieryospp');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5534,'ateebtahir@gmail.com','Khawaja, Ateeb','EMPLOYED',1,'347-251-9865','https://app.revature.com/profile/KMAT/eab7a80a000dc662a9c098b80259c013','ateebtahir');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5535,'suditw@gmail.com','Itwaru, Sudish','EMPLOYED',1,'718-415-0517','https://app.revature.com/profile/sitwaru/8995f5191fdba7a3508ed6e9825863e1','sudish.itwaru');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5536,'danliu277@gmail.com','Liu, Daniel','EMPLOYED',1,'646-275-2027','https://app.revature.com/profile/DanielLiu/8ec745c0558385ae50ac8c25324d7bb3','danliu277');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5537,'guankev@gmail.com','Guan, Kevin','EMPLOYED',1,'347-447-1888','https://app.revature.com/profile/KevinG92/2ba062861641fbf4e956c517983952c4','live:kevguan');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5538,'connelsp@gmail.com','Connelly, Sean','EMPLOYED',1,'718-772-1455','https://app.revature.com/profile/Seanelly/64c09ac289741de8bf7ec0f81f2ad5ad','seanelly08');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5539,'igorgluskin@yahoo.com','Gluskin, Igor','EMPLOYED',1,'347-791-1360','https://app.revature.com/profile/IgorGluskin/ae6866d406461c1c36de8df7c0a1a7a7','igor.gluskin');
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5352,'jgt.tech@gmail.com','Tech, Jonathon','EMPLOYED',2050,'(918) 504-6831',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5350,'kh04548@georgiasouthern.edu','Haas, Kevin','EMPLOYED',2050,'(229) 255-7639',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5351,'ifouche10@gmail.com','Fouche, Issac','EMPLOYED',2050,'(301) 606-8749',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5353,'wyatt.duling@gmail.com','Duling, Wyatt','EMPLOYED',2050,'563-343-3075',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5354,'zhuang4@buffalo.edu','Huang, Jimmy','EMPLOYED',2050,'(917) 916-6881',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5355,'encastillo92@gmail.com','Castillo, Erika','EMPLOYED',2050,'(229) 669-3805',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5356,'m.blanchard@post.com','Blanchard, Martin','DROPPED',2050,'(603) 264-0369',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5357,'manyaam13@gmail.com','Almatar, Manya','DROPPED',2050,'(773) 954-9254',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5358,'dsantonov1990@gmail.com','Antonov, Denis','DROPPED',2050,'(678) 763-6648',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5359,'rrpglad@gmail.com','Peters, Russell','DROPPED',2050,'(240) 678-7156',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5360,'jbspruce@gmail.com','Spruce, Jason','EMPLOYED',2100,'417-793-2382',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5361,'taddetlef@hotmail.com','Detlef, Tad','EMPLOYED',2100,'980-254-4343',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5362,'tylerwelborn91@yahoo.com','Welborn, Tyler','EMPLOYED',2100,'(806) 831-8984',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5363,'yanznln@gmail.com','Lin, Yan','EMPLOYED',2100,'(646) 641-9538',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5540,'tmcdeane@gmail.com','McDeane, Trey','TRAINING',2150,null,null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5402,'justin.atkinson.1990@gmail.com','Atkinson, Justin','EMPLOYED',2100,'267-229-1865',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5400,'nbrown.joshua@yahoo.com','Brown, Joshua','EMPLOYED',2100,'301-917-4594',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5401,'eyekno3w@hotmail.com','Lovell, Jeffrey','EMPLOYED',2100,'414-801-6881',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5450,'tonyhill_1981@yahoo.com','Hill, Anthony','DROPPED',2100,'312-752-0406',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5451,'fjyoung19@gmail.com','Young, Fagbemi','DROPPED',2100,'(757) 478-5280',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5452,'swong8295@gmail.com','Wong, Steven','DROPPED',2100,'(757) 289-6297',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5453,'mro2352@gmail.com','Olson, Matthew','DROPPED',2100,'(573) 382-4546',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5454,'sidak_dhillon@hotmail.com','Dhillon, Sidak','DROPPED',2100,'6783083035',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5455,'dennyayard@yahoo.com','Ayard, Denny','EMPLOYED',2100,'626-394-8606',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5456,'forsbergjj@gmail.com','Forsberg, Justin','EMPLOYED',2150,'(763) 614-9683',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5457,'nbrasco@msn.com','Brasco, Nick','EMPLOYED',2150,'(856) 472-1674',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5458,'alexanderjhajek@gmail.com','Hajek, Alexander','EMPLOYED',2150,'(507) 990-7261',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5459,'wenyuan.will@gmail.com','Wan, William','EMPLOYED',2150,'(908) 616-7543',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5460,'mr.eric.erwin@gmail.com','Erwin, Eric','EMPLOYED',2150,'(701) 500-9782',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5461,'lukehboggs@gmail.com','Boggs, Luke','EMPLOYED',2150,'(630) 338-6039',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5462,'patz1@umbc.edu','Zebron, Patrick','EMPLOYED',2150,'443-668-9955',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5463,'wjandrz@earthlink.net','Andrzejewski, Walter','EMPLOYED',2150,'(813) 892-2173',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5464,'wheeler146@yahoo.com','Wheeler, Justin','EMPLOYED',2150,'(760) 508-2059',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5465,'alex.michels94@hotmail.com','Michels, Alex','EMPLOYED',2150,'(661) 435-3844',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5466,'christopherlolney@gmail.com','Olney, Chris','EMPLOYED',2150,'(270) 535-1997',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5467,'bookofbromon@gmail.com','Smith, Carter','EMPLOYED',2150,'(402) 650-7288',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5468,'starrv2011@gmail.com','Starr, Valencia','DROPPED',2150,'347-770-6819',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5469,'hrich558@live.kutztown.edu','Richiez, Hector','DROPPED',2150,'(347) 247-9731',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5470,'patterdl@clarkson.edu','Patterson, Dalton','DROPPED',2150,'(518) 481-7979',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5471,'kotayaaron@yahoo.com','Kotay Jr., Aaron','DROPPED',2150,'(704) 412-0890',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5472,'barkercbel@gmail.com','Barker, Cory','DROPPED',2150,'(360) 204-6555',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5473,'dominicjb4@hotmail.com','Bartholomeo, Dominic','DROPPED',2150,'757-327-8076',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5474, 'dschrute@mailinator.com','Schrute, Dwight','TRAINING',3000,'700-864-1234',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5475, 'jhalpert@mailinator.com','Halpert, Jim','TRAINING',3000,'700-864-2345',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5477, 'amartin@mailinator.com','Martin, Angela','TRAINING',2,'700-864-4567',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5478, 'kmalone@mailinator.com','Malone, Kevin','TRAINING',2,'700-864-5678',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5479, 'abernard@mailinator.com','Bernard, Andy','TRAINING',2,'700-864-6789',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5480, 'gadams@mailinator.com','Adams, Gary','TRAINING',3002,'700-864-7890',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5481, 'elawrence@mailinator.com','Lawrence, Elaine','TRAINING',3002,'700-864-8901',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5482, 'qleyton@mailinator.com','Leyton, Quinn','TRAINING',3003,'700-864-9012',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5483, 'dcoke@mailinator.com','Coke, Donovan','TRAINING',3003,'700-864-0123',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5484,'bparish@mailinator.com','Parish, Brian','TRAINING',3004,'700-865-1234',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5485,'tbrewster@mailinator.com','Brewster, Tera','TRAINING',3004,'700-865-2345',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5486,'gjohnson@mailinator.com','Johnson, Garrett','EMPLOYED',3005,'700-865-3456',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5487,'kwood@mailinator.com','Wood, Kelly','EMPLOYED',3005,'700-865-4567',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5488,'mrose@mailinator.com','Rose, Marissa','DROPPED',3006,'700-865-5678',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5489,'lhex@mailinator.com','Hex, Leonard','TRAINING',3006,'700-865-6789',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5490, 'sgermanotta@mailinator.com','Germanotta, Stefani','DROPPED',3003,'700-865-7890',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID, RECRUITER_NAME, COLLEGE, DEGREE, MAJOR, TECH_SCREENER_NAME, REVPRO_PROJECT_COMPLETION) values (6000,'bankole726@gmail.com','Ben, Nemec','EMPLOYED',3,'3476527223',null,null, 'Jurczak, Nick', 'UW-Platteville', 'Bachelors', 'Computer Science', 'Some person', '50');

-- TRAINERS --
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'patrick@revature.com', 'Patrick Walsh', 'Lead Trainer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'pjw6193@hotmail.com', 'Dan Pickles', 'Lead Trainer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ravi.cto@revature.com', 'Ravi Singh', 'Vice President of Technology', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'karan.svp@revature.com', 'Karan Dhirar', 'Technology Manager', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'brian.retired@revature.com', 'Brian Connolly', 'Senior Java Developer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'genesis.bonds@revature.com', 'Genesis Bonds', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ankit.garg@revature.com', 'Ankit Garg', 'Lead Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ryan.lessley@revature.com', 'Ryan Lessley', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'steven.kelsey@revature.com', 'Steven Kelsey', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'emily.higgins@revature.com', 'Emily Higgins', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'taylor.kemper@revature.com', 'Taylor Kemper', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'richard.orr@revature.com', 'Richard Orr', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'nickolas.jurczak@revature.com', 'Nickolas Jurczak', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'august.duet@revature.com', 'August Duet', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'yuvarajd@revature.com', 'Yuvaraj Damodaran', 'Lead Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'fred.belotte@revature.com', 'Fred Belotte', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'mehrab.rahman@revature.com', 'Mehrab Rahman', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'peter.alagna@revature.com', 'Peter Alagna', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'stanleym@revature.com', 'Stanley Medikonda', 'Staging Manager', 'ROLE_STAGING');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'grawyne@gmail.com', 'Gray Wynne', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'owallace@mailinator.com', 'Orson Wallace', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'slevinson@mailinator.com', 'Shelby Levinson', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'wpayne@mailinator.com', 'Walter Payne', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'nchurch@mailinator.com', 'Natalie Church', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'aradcliff@mailinator.com', 'Archer Radcliff', 'Junior Trainer', 'ROLE_TRAINER');
--------------------------------------------------------------------------------------------------------------------MAKE PANEL ROLE
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'rajeshy@revature.com', 'Rajesh Yamunachari', 'Senior Technical Manager', 'ROLE_PANEL');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'raghavan@revature.com', 'Raghavan Swaminathan', 'Senior Technical Manager', 'ROLE_PANEL');
-------------TRAINER END-------------
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'external@revature.com', 'External Trainer', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'enrollmentadmin@revature.com', 'Enrollment Admin', 'Bot User', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'calibot@revature.com', 'Caliber Bot', 'Bot User', 'ROLE_VP');
