spring:
  application:
    name: ERS-service
  profiles:
    active: local

  h2.datasource:
    url: jdbc:h2:mem:mybatis;Mode=Oracle
    platform: h2
    enable: true
    path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oct22-java-demo.craonmf7k4ob.us-east-1.rds.amazonaws.com:1521/ORCL
    username: oct22_java_demo
    password: Myhome1049

mybatis.type-aliases-package: com.mybatis.model
mybatis.mapper-locations: mybatis/*.xml

bankaccount.interval.time: 5
